In [22]:
def section():
    print(f"\n{'*' * 10} SECTION {'*' * 10} \n")


def divider():
    print(f"\n\t{'-' * 10} DIVIDER {'-' * 10} \n")

In [23]:
symbols = '$ç¥∆†ø'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))
print(symbols)

# Equivalently: This code below is much readable and faster

symbols = '$ç¥∆†ø'
codes = [ord(symbol) for symbol in symbols]
print(symbols)


x = 'ABC'
dummy = [ord(x) for x in x]
print(x)
print(dummy)
# prior to python 2 the value of x would have leaked

$ç¥∆†ø
$ç¥∆†ø
ABC
[65, 66, 67]


## Listcomp vs map and filter

In [24]:
symbols = '$¢£¥€¤'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
print(beyond_ascii)


# Using map
beyond_ascii = list(filter(lambda c: c > 127, map(ord, symbols)))
print(beyond_ascii)
# readability kinda suffers

# Cartesian products
colors = ['black', 'white']
sizes = ['S', 'M', 'L']

tshirts = [(color, size) for color in colors for size in sizes]

print(tshirts)

# Cartesian product in generator expression
for tshirt in ('%s %s' % (c, s) for c in colors for s in sizes):
    print(tshirt)
# The expression yield items one by one and no list is created at the end


[162, 163, 165, 8364, 164]
[162, 163, 165, 8364, 164]
[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
black S
black M
black L
white S
white M
white L


## Generator expressions
used for initializing other sequences types such as tuple, array and others

In [25]:
symbols = '$¢£¥€¤'
codes = tuple(ord(symbol) for symbol in symbols)
print(codes)

import array
codes = array.array('I', (ord(symbol) for symbol in symbols))
print(codes)

# Tuples
# Tuples as records

lax_coordinates = (33.9425, -118.408056)
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'), ('BRA', 'CE342567'), ('ESP', 'XDA205856')]

for passport in sorted(traveler_ids):
    print('%s/%s' % passport)


# Tuple unpacking
b = 10
a = 0
a, b = b, a
print(a, b)

import os

_, filename = os.path.split('../The Python Data Model/ex-code.py')
print(_)
print(filename)


# using * to grab excess items
a, b, *rest = range(5)
print(a, b, rest)

(36, 162, 163, 165, 8364, 164)
array('I', [36, 162, 163, 165, 8364, 164])
BRA/CE342567
ESP/XDA205856
USA/31195855
10 0
../The Python Data Model
ex-code.py
0 1 [2, 3, 4]


## NAMED TUPLES

In [26]:
from collections import namedtuple
# City = namedtuple('City', ['name', 'country', 'population', 'coordinates'])
# OR
City = namedtuple('City', 'name country population coordinates')

tokyo = City('Tokyo', 'JP', 36.689722, (35.689722, 139.691667))
print(tokyo)
print(tokyo.coordinates)
print(tokyo.coordinates[0])

coord = tokyo.coordinates
print(coord)

print(City._fields)
print(City._field_defaults)

Latlong = namedtuple('Latlong', 'lat log')

delhi_data = ('Delhi NCR', 'IN', 21.935, Latlong(28.613, 77.2088))
delhi = City._make(delhi_data)
print(delhi)
print(delhi._asdict())

for key, value in delhi._asdict().items():
    print(key + ':', value)

items = [n for n in range(0, 100) if n % 2 == 0] + list([0, 0, 0, 0])
print(items.count(0)) # count all occurrences of zero

City(name='Tokyo', country='JP', population=36.689722, coordinates=(35.689722, 139.691667))
(35.689722, 139.691667)
35.689722
(35.689722, 139.691667)
('name', 'country', 'population', 'coordinates')
{}
City(name='Delhi NCR', country='IN', population=21.935, coordinates=Latlong(lat=28.613, log=77.2088))
{'name': 'Delhi NCR', 'country': 'IN', 'population': 21.935, 'coordinates': Latlong(lat=28.613, log=77.2088)}
name: Delhi NCR
country: IN
population: 21.935
coordinates: Latlong(lat=28.613, log=77.2088)
5


## Why slices and range exclude the last item

In [27]:
l = [10, 20, 30, 40, 50, 60]
print(l)
print(l[:2])
print(l[2:])
print(l[:3])
print(l[3:])
print(l[3::2])


# Slice objects
""" How Python interprets slice notations """
s = 'bicycle'
print(s[::3]) # with 3 steps
print(s[::-1])
print(s[::-2])


invoice = """
    0.....6.................................40...........52...55.......
    1909  Pimoroni PiBrella                     $17.50      3    $52.50
    1909  Pimoroni PiBrella                     $17.50      3    $52.50
    1909  Pimoroni PiBrella                     $17.50      3    $52.50
    1909  Pimoroni PiBrella                     $17.50      3    $52.50
    1909  Pimoroni PiBrella                     $17.50      3    $52.50
"""

SKU = slice(0, 6)
DESCRIPTION = slice(6, 40)
UNIT_PRICE  = slice(40, 52)
QUANTITY    = slice(52, 55)
ITEM_TOTAL  = slice(55, None)
line_items = invoice.split('\n')[2:]
for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

[10, 20, 30, 40, 50, 60]
[10, 20]
[30, 40, 50, 60]
[10, 20, 30]
[40, 50, 60]
[40, 60]
bye
elcycib
eccb
        $17. 09  Pimoroni PiBrella             
        $17. 09  Pimoroni PiBrella             
        $17. 09  Pimoroni PiBrella             
        $17. 09  Pimoroni PiBrella             
        $17. 09  Pimoroni PiBrella             
 


## Multi-dimensional slicing and ellipsis

In [28]:
multi = [
    [[10, 0, 3], [10, 0, 3], [10, 0, 3]],
    [40, 0, 3],
    [10, 20, 3],
    [10, 60, 3],
]

## Assigning to Slices

In [29]:
l = list(range(10))
print(l)

l[2:5] = [20, 30]
print(l)

del l[5:7]
print(l)

l[3::2] = [11, 22]
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 6, 7, 8, 9]
[0, 1, 20, 30, 5, 8, 9]
[0, 1, 20, 11, 5, 22, 9]


## Using + and * with sequences
   - both operands must be of the same type

In [30]:
l = [i for i in range(10)]
print(l)
five_ls = l * 5
print(five_ls)

print('abcd' * 5)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
abcdabcdabcdabcdabcd


## Pitfalls: Building `lists of list`

In [31]:
board = [[i] * 3 for i in range(3)]
print(board)
board = [['-'] * 3 for i in range(3)]
print(board)

board[1][2] = 'X'
print(board)

weird_board = [['_'] * 3] * 3
print(weird_board)
weird_board[1][2] = '0'
print(weird_board) # Now noticed the difference: the same reference were used for the three lists

[[0, 0, 0], [1, 1, 1], [2, 2, 2]]
[['-', '-', '-'], ['-', '-', '-'], ['-', '-', '-']]
[['-', '-', '-'], ['-', '-', 'X'], ['-', '-', '-']]
[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]
[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]


## Augmented assignment with sequences

In [32]:
a = 0
b = 2
a += b
print(a)

l = [1, 2, 3]
print(id(l))
l *= 2
print(l)

t = (1, 2, 3)
print(id(t))
t *= 2
print(t)
print(id(t))


2
4520529216
[1, 2, 3, 1, 2, 3]
4520394432
(1, 2, 3, 1, 2, 3)
4436616288


## A += assignment puzzler

In [33]:
t = (1, 2, [30, 40])
print(t)
t[2].append(50)
# t[2] += [50, 60]
print(t)

(1, 2, [30, 40])
(1, 2, [30, 40, 50])


## Visualizing Python Bytecode

In [34]:
import dis
dis.dis('a += b')

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 INPLACE_ADD
              6 STORE_NAME               0 (a)
              8 LOAD_CONST               0 (None)
             10 RETURN_VALUE


## list.sort and the sorted built-in functions

In [35]:
my_str = [
    "kelvin",
    "Kelvin",
    "Mark",
    "jon",
]

print(my_str)
print(my_str.sort())

my_str = sorted(my_str, key=str.lower, reverse=True)
print(my_str)

fruits = ['grape', 'raspberry', 'apple', 'banana']
print(fruits)
print(fruits.sort())
print(sorted(fruits))
print(sorted(fruits, key=len))

['kelvin', 'Kelvin', 'Mark', 'jon']
None
['Mark', 'Kelvin', 'kelvin', 'jon']
['grape', 'raspberry', 'apple', 'banana']
None
['apple', 'banana', 'grape', 'raspberry']
['apple', 'grape', 'banana', 'raspberry']


## Searching with bisect

In [36]:
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'


def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)
        offset = position * '  |'
        if position == 0:
            offset += '  |'
        print(ROW_FMT.format(needle, position, f"{offset} search value: "))


if __name__ == "__main__":
    if sys.argv[-1] == 'left':
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect

    print('Demo:', bisect_fn.__name__)
    print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)


nc = bisect.bisect_left(HAYSTACK, 15)
print(nc)
nc = bisect.bisect_right(HAYSTACK, 15)
print(nc)

Demo: bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  | search value: 31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  | search value: 30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  | search value: 29
23 @ 11      |  |  |  |  |  |  |  |  |  |  | search value: 23
22 @  9      |  |  |  |  |  |  |  |  | search value: 22
10 @  5      |  |  |  |  | search value: 10
 8 @  5      |  |  |  |  | search value: 8 
 5 @  3      |  |  | search value: 5 
 2 @  1      | search value: 2 
 1 @  1      | search value: 1 
 0 @  0      | search value: 0 
6
7


## Inserting with bisect.insort
 - insort sorts a sequences and keeps it that way

In [37]:
import bisect
import random

SIZE = 7
random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE * 2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)


10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


## When list is not the answer!

Arrays:

In [38]:
from array import array
from random import random

# floats = array('d', (random() for i in range(10**7)))
# print(floats[-1])
#
# fp = open('floats.bin', 'wb')
# fpt = open('floats.txt', 'w')
#
# floats.tofile(fp)
# fp.close()
#
# floats2 = array('d')
# fp = open('floats.bin', 'rb')
# floats2.fromfile(fp, 10**7)
# fp.close()
#
# print(floats2[-1])
# print(floats2 == floats)


## Memory Views

In [39]:
numbers = array('h', [-2, -1, 0, 1, 2])
memv = memoryview(numbers)
print(len(memv))

print(memv[0])
memv_oct = memv.cast('B')
print(memv_oct.tolist())
memv_oct[5] = 2

section()

5
-2
[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

********** SECTION ********** 



## Numpy and Scipy

In [40]:
import numpy

a = numpy.arange(12)
print(a)
print(type(a))
print(a.shape)

a.shape = 3, 4 # three rows and 4 columns matrix
print(a)
divider()

print(a[2])
divider()
print(a[:])
divider()
print(a[...])
divider()
print("Row 2: index:1 ==>", a[2, 1])
divider()
print("Column 1 ==>", a[:, 1])
divider()
print("A: Transpose: ==>", a.transpose())

section()

from time import perf_counter as pc

try:
    floats = numpy.loadtxt('floats-10M-lines.txt')
    print(floats[-3:]) # get the last three numbers
    floats *= .5
    print(floats[-3:])

    to = pc(); floats /= 3; pc() - to
    numpy.save('float-10M', floats)
    floats = numpy.load('floats-10M,npy', 'r+')
    floats *= 6
    print(floats[-3:])

except IOError:
    print("File not Found")

section()

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

	---------- DIVIDER ---------- 

[ 8  9 10 11]

	---------- DIVIDER ---------- 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

	---------- DIVIDER ---------- 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

	---------- DIVIDER ---------- 

Row 2: index:1 ==> 9

	---------- DIVIDER ---------- 

Column 1 ==> [1 5 9]

	---------- DIVIDER ---------- 

A: Transpose: ==> [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

********** SECTION ********** 

File not Found

********** SECTION ********** 



## Deques and queues

In [41]:
from collections import deque

dc = deque()
dc.append('kelvin')
print(dc)
divider()
dq = deque(range(10), maxlen=10)
print(dq)
dq.rotate(-4)
print(dq)
dq.appendleft(-1)
print(dq)
dq.extend([11, 22, 33])
print(dq)
dq.extendleft([10, 20, 30, 40])
print(dq)

deque(['kelvin'])

	---------- DIVIDER ---------- 

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)
deque([4, 5, 6, 7, 8, 9, 0, 1, 2, 3], maxlen=10)
deque([-1, 4, 5, 6, 7, 8, 9, 0, 1, 2], maxlen=10)
deque([6, 7, 8, 9, 0, 1, 2, 11, 22, 33], maxlen=10)
deque([40, 30, 20, 10, 6, 7, 8, 9, 0, 1], maxlen=10)
